---

plugins_list:
    - bouncycastle-api
    - credentials
    - momentjs
    - ssh-credentials
    - durable-task
    - structs
    - workflow-step-api
    - pipeline-stage-view
    - workflow-scm-step
    - docker-commons
    - git-client
    - script-security
    - junit
    - git-server
    - matrix-project
    - display-url-api
    - mailer
    - git
    - ansicolor
    - cloudbees-folder
    - windows-slaves
    - docker-workflow
    - icon-shim
    - matrix-auth
    - antisamy-markup-formatter
    - workflow-support
    - build-with-parameters
    - branch-api
    - token-macro
    - Parameterized-Remote-Trigger
    - workflow-cps-global-lib
    - build-flow-plugin
    - pam-auth
    - ldap
    - pipeline-milestone-step
    - external-monitor-job
    - javadoc
    - ant
    - run-condition
    - scm-api
    - maven-plugin
    - pipeline-rest-api
    - conditional-buildstep
    - parameterized-trigger
    - envfile
    - workflow-api
    - jquery-detached
    - ace-editor
    - workflow-cps
    - pipeline-stage-step
    - pipeline-build-step
    - pipeline-input-step
    - workflow-job
    - handlebars
    - pipeline-graph-analysis
    - workflow-durable-task-step
    - plain-credentials
    - credentials-binding
    - pipeline-model-api
    - workflow-basic-steps
    - pipeline-stage-tags-metadata
    - authentication-tokens
    - pipeline-model-declarative-agent
    - workflow-multibranch
    - pipeline-model-definition
    - workflow-aggregator
pip_dependency_for_azure: |
  Jinja2==2.8
  MarkupSafe==0.23
  PyYAML==3.12
  ansible==2.1.2.0
  azure==2.0.0rc6
  azure-batch==1.1.0
  azure-common==1.1.4
  azure-graphrbac==0.30.0rc6
  azure-mgmt==0.30.0rc6
  azure-mgmt-authorization==0.30.0rc6
  azure-mgmt-batch==2.0.0
  azure-mgmt-cdn==0.30.0rc6
  azure-mgmt-cognitiveservices==0.30.0rc6
  azure-mgmt-commerce==0.30.0rc6
  azure-mgmt-compute==0.32.0
  azure-mgmt-containerregistry==0.1.0
  azure-mgmt-datalake-analytics==0.1.0
  azure-mgmt-datalake-nspkg==1.0.0
  azure-mgmt-datalake-store==0.1.0
  azure-mgmt-devtestlabs==1.0.0
  azure-mgmt-dns==0.30.0rc6
  azure-mgmt-eventhub==0.1.0
  azure-mgmt-iothub==0.1.0
  azure-mgmt-keyvault==0.30.0
  azure-mgmt-logic==1.0.0
  azure-mgmt-media==0.1.0
  azure-mgmt-network==0.30.0
  azure-mgmt-notificationhubs==0.30.0
  azure-mgmt-nspkg==1.0.0
  azure-mgmt-powerbiembedded==0.30.0rc6
  azure-mgmt-redis==2.0.0
  azure-mgmt-resource==0.31.0
  azure-mgmt-scheduler==1.0.0
  azure-mgmt-servermanager==1.0.0
  azure-mgmt-servicebus==0.1.0
  azure-mgmt-sql==0.1.0
  azure-mgmt-storage==0.30.0rc6
  azure-mgmt-trafficmanager==0.30.0rc6
  azure-mgmt-web==0.30.1
  azure-monitor==0.0.1
  azure-nspkg==1.0.0
  azure-servicebus==0.20.3
  azure-servicemanagement-legacy==0.20.5
  boto==2.43.0
  certifi==2016.9.26
  chardet==2.3.0
  configparser==3.5.0
  enum34==1.1.6
  futures==3.0.5
  isodate==0.5.4
  keyring==10.0.2
  msrest==0.4.4
  msrestazure==0.4.7
  oauthlib==2.0.0
  paramiko==2.0.2
  pyasn1==0.1.9
  pycrypto==2.6.1
  python-dateutil==2.6.0
  requests==2.12.1
  requests-oauthlib==0.7.0
  six==1.10.0
  wsgiref==0.1.2