provider:
  - azure:
    - config:
      - credentials:
          subscription_id: 51df121a-2371-45a4-8387-d72ef028239f
          client_id: 03ead528-650b-4c11-8abc-624aa2569c4a
          secret: FSgtsqf8TuV6Sb2mrdVuTDozc43HYY9ltksCw/ytbmk=
          tenant: d5d2540f-f60a-45ad-86a9-e2e792ee6669
      - server_size: Standard_D1_v2
services:
 -
   name: t24dev
   stack: t24
   owner: marketplace
   region: ukwest
   cidr: 10.10.0.0/16
   dns_servers: 8.8.8.8,4.4.4.4
   subnet: 10.10.1.0/24
   servers:
    - name: t24
      count: 1
 -
   name: temenosdevcore 
   stack: core
   owner: marketplace
   region: ukwest
   cidr: 10.10.0.0/16
   dns_servers: 8.8.8.8,4.4.4.4
   subnet: 10.10.1.0/24
   servers:
    - name: gitlab
      count: 1
    - name: yum
      count: 1
    - name: jenkins
      count: 1
 -
   name: cluster1
   stack: oscp
   owner: marketplace
   region: ukwest
   cidr: 10.10.0.0/16
   dns_servers: 8.8.8.8,4.4.4.4
   subnet: 10.10.1.0/24
   load_balancers:
    - name: gitlab
      be_servers: gitlab
      health_port: 8081
      health_protocol: 'Http'
      health_path: '/users/sign_in'
      rules:
       - name: web
         protocol: 'Tcp'
         frontend_port: 80
         backend_port: 8081
    - name: console
      domain: cluster1
      be_servers: master
      health_port: 443
      health_protocol: 'Tcp'
      rules:
       - name: ssl
         protocol: 'Tcp'
         frontend_port: 443
         backend_port: 443
    - name: apps
      domain: '*.apps.cluster1'
      be_servers: node_infra
      health_port: 443
      health_protocol: 'Tcp'
      rules:
       - name: router-http
         protocol: 'Tcp'
         frontend_port: 80
         backend_port: 80
       - name: router-ssl
         protocol: 'Tcp'
         frontend_port: 443
         backend_port: 443
   servers:
    - name: gitlab
      count: 1
      lb: true
    - name: storage
      count: 1
    - name: formation
      count: 1
    - name: master
      count: 1
      lb: true
    - name: node_infra
      count: 1
      lb: true
    - name: node_worker
      count: 1
global:
 user: mpadmin

