credentials:
  azure:
    subscription_id: 51df121a-2371-45a4-8387-d72ef028239f
    client_id: 03ead528-650b-4c11-8abc-624aa2569c4a
    secret: FSgtsqf8TuV6Sb2mrdVuTDozc43HYY9ltksCw/ytbmk=
    tenant: d5d2540f-f60a-45ad-86a9-e2e792ee6669
  gitlab:
    url: "https://gitlab.temenos.cloud"
    token: "FHcv_bHjHnAvd6uug7x_"
  jenkins:
    url: "http://51.141.7.30:8080"
    user: "admin"
    password: "Blue1Sky"
defaults:
  resource_group_name: "mpdevtestrg"
  storage_account_name: "mpdevtestsa"
test:
  environment_ids:
    - "abcdefghijk0"
    - "abcdefghijk1"
    - "abcdefghijk2"
    - "abcdefghijk3"
    - "abcdefghijk4"
    - "abcdefghijk5"
    - "abcdefghijk6"
    - "abcdefghijk7"
    - "abcdefghijk8"
    - "abcdefghijk9"
  scale_to: 1
  concurrent_deployments: 3
  api_host: "127.0.0.1"
  api_port: 5000
  # website_url: "http://t24-{{id}}.dev.temenos.cloud/BrowserWeb/"
  website_url: "https://github.com/"
  flask_testing: false
  flask_debug: false
