---
-   name: Testing for Dataloop image
    shell: docker ps | grep dataloop
    register: dlcontainer
    ignore_errors: True
    changed_when: "dlcontainer.rc != 0"
-   name: "Ensure Docker container installed for monitoring"
    shell: docker run -d -e API_KEY=d2fc7190-7176-4415-b498-814e52423823 --volume=/:/rootfs:ro --volume=/var/run:/var/run:rw --volume=/sys:/sys:ro --volume=/var/lib/docker/:/var/lib/docker:ro --privileged dataloop/dataloop-docker:centos7
    when: dlcontainer.rc == 1
-   name: "Set up sudoers for lvs monitoring"
    copy: src=files/dataloop.sudoers dest=/etc/sudoers.d/dataloop owner=root group=root mode=0644
-   name: "Disable require tty"
    lineinfile: dest=/etc/sudoers regexp="^Defaults    requiretty" line="#Defaults    requiretty" 
