---
# tasks file for java
- name: Add JAVA_HOME to the system profile
  template: src=etc_profile.d_java_home.sh.j2 dest=/etc/profile.d/java_home.sh owner=root group=root


# include the distro-specific stuff
- include: debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- include: rhel.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
